// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CdcAuthUsers is the predicate function for cdcauthusers builders.
type CdcAuthUsers func(*sql.Selector)

// EmailTemplate is the predicate function for emailtemplate builders.
type EmailTemplate func(*sql.Selector)
