// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/ngdangkietswe/swe-notification-service/data/ent/cdcauthusers"
	"github.com/ngdangkietswe/swe-notification-service/data/ent/predicate"
)

// CdcAuthUsersQuery is the builder for querying CdcAuthUsers entities.
type CdcAuthUsersQuery struct {
	config
	ctx        *QueryContext
	order      []cdcauthusers.OrderOption
	inters     []Interceptor
	predicates []predicate.CdcAuthUsers
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CdcAuthUsersQuery builder.
func (cauq *CdcAuthUsersQuery) Where(ps ...predicate.CdcAuthUsers) *CdcAuthUsersQuery {
	cauq.predicates = append(cauq.predicates, ps...)
	return cauq
}

// Limit the number of records to be returned by this query.
func (cauq *CdcAuthUsersQuery) Limit(limit int) *CdcAuthUsersQuery {
	cauq.ctx.Limit = &limit
	return cauq
}

// Offset to start from.
func (cauq *CdcAuthUsersQuery) Offset(offset int) *CdcAuthUsersQuery {
	cauq.ctx.Offset = &offset
	return cauq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cauq *CdcAuthUsersQuery) Unique(unique bool) *CdcAuthUsersQuery {
	cauq.ctx.Unique = &unique
	return cauq
}

// Order specifies how the records should be ordered.
func (cauq *CdcAuthUsersQuery) Order(o ...cdcauthusers.OrderOption) *CdcAuthUsersQuery {
	cauq.order = append(cauq.order, o...)
	return cauq
}

// First returns the first CdcAuthUsers entity from the query.
// Returns a *NotFoundError when no CdcAuthUsers was found.
func (cauq *CdcAuthUsersQuery) First(ctx context.Context) (*CdcAuthUsers, error) {
	nodes, err := cauq.Limit(1).All(setContextOp(ctx, cauq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cdcauthusers.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) FirstX(ctx context.Context) *CdcAuthUsers {
	node, err := cauq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CdcAuthUsers ID from the query.
// Returns a *NotFoundError when no CdcAuthUsers ID was found.
func (cauq *CdcAuthUsersQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cauq.Limit(1).IDs(setContextOp(ctx, cauq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cdcauthusers.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cauq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CdcAuthUsers entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CdcAuthUsers entity is found.
// Returns a *NotFoundError when no CdcAuthUsers entities are found.
func (cauq *CdcAuthUsersQuery) Only(ctx context.Context) (*CdcAuthUsers, error) {
	nodes, err := cauq.Limit(2).All(setContextOp(ctx, cauq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cdcauthusers.Label}
	default:
		return nil, &NotSingularError{cdcauthusers.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) OnlyX(ctx context.Context) *CdcAuthUsers {
	node, err := cauq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CdcAuthUsers ID in the query.
// Returns a *NotSingularError when more than one CdcAuthUsers ID is found.
// Returns a *NotFoundError when no entities are found.
func (cauq *CdcAuthUsersQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cauq.Limit(2).IDs(setContextOp(ctx, cauq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cdcauthusers.Label}
	default:
		err = &NotSingularError{cdcauthusers.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cauq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CdcAuthUsersSlice.
func (cauq *CdcAuthUsersQuery) All(ctx context.Context) ([]*CdcAuthUsers, error) {
	ctx = setContextOp(ctx, cauq.ctx, ent.OpQueryAll)
	if err := cauq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CdcAuthUsers, *CdcAuthUsersQuery]()
	return withInterceptors[[]*CdcAuthUsers](ctx, cauq, qr, cauq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) AllX(ctx context.Context) []*CdcAuthUsers {
	nodes, err := cauq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CdcAuthUsers IDs.
func (cauq *CdcAuthUsersQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cauq.ctx.Unique == nil && cauq.path != nil {
		cauq.Unique(true)
	}
	ctx = setContextOp(ctx, cauq.ctx, ent.OpQueryIDs)
	if err = cauq.Select(cdcauthusers.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cauq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cauq *CdcAuthUsersQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cauq.ctx, ent.OpQueryCount)
	if err := cauq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cauq, querierCount[*CdcAuthUsersQuery](), cauq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) CountX(ctx context.Context) int {
	count, err := cauq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cauq *CdcAuthUsersQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cauq.ctx, ent.OpQueryExist)
	switch _, err := cauq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cauq *CdcAuthUsersQuery) ExistX(ctx context.Context) bool {
	exist, err := cauq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CdcAuthUsersQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cauq *CdcAuthUsersQuery) Clone() *CdcAuthUsersQuery {
	if cauq == nil {
		return nil
	}
	return &CdcAuthUsersQuery{
		config:     cauq.config,
		ctx:        cauq.ctx.Clone(),
		order:      append([]cdcauthusers.OrderOption{}, cauq.order...),
		inters:     append([]Interceptor{}, cauq.inters...),
		predicates: append([]predicate.CdcAuthUsers{}, cauq.predicates...),
		// clone intermediate query.
		sql:  cauq.sql.Clone(),
		path: cauq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CdcAuthUsers.Query().
//		GroupBy(cdcauthusers.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cauq *CdcAuthUsersQuery) GroupBy(field string, fields ...string) *CdcAuthUsersGroupBy {
	cauq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CdcAuthUsersGroupBy{build: cauq}
	grbuild.flds = &cauq.ctx.Fields
	grbuild.label = cdcauthusers.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.CdcAuthUsers.Query().
//		Select(cdcauthusers.FieldUsername).
//		Scan(ctx, &v)
func (cauq *CdcAuthUsersQuery) Select(fields ...string) *CdcAuthUsersSelect {
	cauq.ctx.Fields = append(cauq.ctx.Fields, fields...)
	sbuild := &CdcAuthUsersSelect{CdcAuthUsersQuery: cauq}
	sbuild.label = cdcauthusers.Label
	sbuild.flds, sbuild.scan = &cauq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CdcAuthUsersSelect configured with the given aggregations.
func (cauq *CdcAuthUsersQuery) Aggregate(fns ...AggregateFunc) *CdcAuthUsersSelect {
	return cauq.Select().Aggregate(fns...)
}

func (cauq *CdcAuthUsersQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cauq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cauq); err != nil {
				return err
			}
		}
	}
	for _, f := range cauq.ctx.Fields {
		if !cdcauthusers.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cauq.path != nil {
		prev, err := cauq.path(ctx)
		if err != nil {
			return err
		}
		cauq.sql = prev
	}
	return nil
}

func (cauq *CdcAuthUsersQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CdcAuthUsers, error) {
	var (
		nodes = []*CdcAuthUsers{}
		_spec = cauq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CdcAuthUsers).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CdcAuthUsers{config: cauq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cauq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cauq *CdcAuthUsersQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cauq.querySpec()
	_spec.Node.Columns = cauq.ctx.Fields
	if len(cauq.ctx.Fields) > 0 {
		_spec.Unique = cauq.ctx.Unique != nil && *cauq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cauq.driver, _spec)
}

func (cauq *CdcAuthUsersQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cdcauthusers.Table, cdcauthusers.Columns, sqlgraph.NewFieldSpec(cdcauthusers.FieldID, field.TypeUUID))
	_spec.From = cauq.sql
	if unique := cauq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cauq.path != nil {
		_spec.Unique = true
	}
	if fields := cauq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cdcauthusers.FieldID)
		for i := range fields {
			if fields[i] != cdcauthusers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cauq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cauq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cauq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cauq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cauq *CdcAuthUsersQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cauq.driver.Dialect())
	t1 := builder.Table(cdcauthusers.Table)
	columns := cauq.ctx.Fields
	if len(columns) == 0 {
		columns = cdcauthusers.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cauq.sql != nil {
		selector = cauq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cauq.ctx.Unique != nil && *cauq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cauq.predicates {
		p(selector)
	}
	for _, p := range cauq.order {
		p(selector)
	}
	if offset := cauq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cauq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CdcAuthUsersGroupBy is the group-by builder for CdcAuthUsers entities.
type CdcAuthUsersGroupBy struct {
	selector
	build *CdcAuthUsersQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (caugb *CdcAuthUsersGroupBy) Aggregate(fns ...AggregateFunc) *CdcAuthUsersGroupBy {
	caugb.fns = append(caugb.fns, fns...)
	return caugb
}

// Scan applies the selector query and scans the result into the given value.
func (caugb *CdcAuthUsersGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, caugb.build.ctx, ent.OpQueryGroupBy)
	if err := caugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CdcAuthUsersQuery, *CdcAuthUsersGroupBy](ctx, caugb.build, caugb, caugb.build.inters, v)
}

func (caugb *CdcAuthUsersGroupBy) sqlScan(ctx context.Context, root *CdcAuthUsersQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(caugb.fns))
	for _, fn := range caugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*caugb.flds)+len(caugb.fns))
		for _, f := range *caugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*caugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := caugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CdcAuthUsersSelect is the builder for selecting fields of CdcAuthUsers entities.
type CdcAuthUsersSelect struct {
	*CdcAuthUsersQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (caus *CdcAuthUsersSelect) Aggregate(fns ...AggregateFunc) *CdcAuthUsersSelect {
	caus.fns = append(caus.fns, fns...)
	return caus
}

// Scan applies the selector query and scans the result into the given value.
func (caus *CdcAuthUsersSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, caus.ctx, ent.OpQuerySelect)
	if err := caus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CdcAuthUsersQuery, *CdcAuthUsersSelect](ctx, caus.CdcAuthUsersQuery, caus, caus.inters, v)
}

func (caus *CdcAuthUsersSelect) sqlScan(ctx context.Context, root *CdcAuthUsersQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(caus.fns))
	for _, fn := range caus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*caus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := caus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
