// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/ngdangkietswe/swe-notification-service/data/ent/emailtemplate"
)

// EmailTemplateCreate is the builder for creating a EmailTemplate entity.
type EmailTemplateCreate struct {
	config
	mutation *EmailTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTemplateKey sets the "template_key" field.
func (etc *EmailTemplateCreate) SetTemplateKey(s string) *EmailTemplateCreate {
	etc.mutation.SetTemplateKey(s)
	return etc
}

// SetName sets the "name" field.
func (etc *EmailTemplateCreate) SetName(s string) *EmailTemplateCreate {
	etc.mutation.SetName(s)
	return etc
}

// SetSubject sets the "subject" field.
func (etc *EmailTemplateCreate) SetSubject(s string) *EmailTemplateCreate {
	etc.mutation.SetSubject(s)
	return etc
}

// SetBody sets the "body" field.
func (etc *EmailTemplateCreate) SetBody(s string) *EmailTemplateCreate {
	etc.mutation.SetBody(s)
	return etc
}

// SetIsHTML sets the "is_html" field.
func (etc *EmailTemplateCreate) SetIsHTML(b bool) *EmailTemplateCreate {
	etc.mutation.SetIsHTML(b)
	return etc
}

// SetNillableIsHTML sets the "is_html" field if the given value is not nil.
func (etc *EmailTemplateCreate) SetNillableIsHTML(b *bool) *EmailTemplateCreate {
	if b != nil {
		etc.SetIsHTML(*b)
	}
	return etc
}

// SetCreatedAt sets the "created_at" field.
func (etc *EmailTemplateCreate) SetCreatedAt(t time.Time) *EmailTemplateCreate {
	etc.mutation.SetCreatedAt(t)
	return etc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (etc *EmailTemplateCreate) SetNillableCreatedAt(t *time.Time) *EmailTemplateCreate {
	if t != nil {
		etc.SetCreatedAt(*t)
	}
	return etc
}

// SetUpdatedAt sets the "updated_at" field.
func (etc *EmailTemplateCreate) SetUpdatedAt(t time.Time) *EmailTemplateCreate {
	etc.mutation.SetUpdatedAt(t)
	return etc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (etc *EmailTemplateCreate) SetNillableUpdatedAt(t *time.Time) *EmailTemplateCreate {
	if t != nil {
		etc.SetUpdatedAt(*t)
	}
	return etc
}

// SetIsDeleted sets the "is_deleted" field.
func (etc *EmailTemplateCreate) SetIsDeleted(b bool) *EmailTemplateCreate {
	etc.mutation.SetIsDeleted(b)
	return etc
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (etc *EmailTemplateCreate) SetNillableIsDeleted(b *bool) *EmailTemplateCreate {
	if b != nil {
		etc.SetIsDeleted(*b)
	}
	return etc
}

// SetID sets the "id" field.
func (etc *EmailTemplateCreate) SetID(u uuid.UUID) *EmailTemplateCreate {
	etc.mutation.SetID(u)
	return etc
}

// Mutation returns the EmailTemplateMutation object of the builder.
func (etc *EmailTemplateCreate) Mutation() *EmailTemplateMutation {
	return etc.mutation
}

// Save creates the EmailTemplate in the database.
func (etc *EmailTemplateCreate) Save(ctx context.Context) (*EmailTemplate, error) {
	etc.defaults()
	return withHooks(ctx, etc.sqlSave, etc.mutation, etc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (etc *EmailTemplateCreate) SaveX(ctx context.Context) *EmailTemplate {
	v, err := etc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (etc *EmailTemplateCreate) Exec(ctx context.Context) error {
	_, err := etc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (etc *EmailTemplateCreate) ExecX(ctx context.Context) {
	if err := etc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (etc *EmailTemplateCreate) defaults() {
	if _, ok := etc.mutation.IsHTML(); !ok {
		v := emailtemplate.DefaultIsHTML
		etc.mutation.SetIsHTML(v)
	}
	if _, ok := etc.mutation.CreatedAt(); !ok {
		v := emailtemplate.DefaultCreatedAt
		etc.mutation.SetCreatedAt(v)
	}
	if _, ok := etc.mutation.UpdatedAt(); !ok {
		v := emailtemplate.DefaultUpdatedAt
		etc.mutation.SetUpdatedAt(v)
	}
	if _, ok := etc.mutation.IsDeleted(); !ok {
		v := emailtemplate.DefaultIsDeleted
		etc.mutation.SetIsDeleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (etc *EmailTemplateCreate) check() error {
	if _, ok := etc.mutation.TemplateKey(); !ok {
		return &ValidationError{Name: "template_key", err: errors.New(`ent: missing required field "EmailTemplate.template_key"`)}
	}
	if v, ok := etc.mutation.TemplateKey(); ok {
		if err := emailtemplate.TemplateKeyValidator(v); err != nil {
			return &ValidationError{Name: "template_key", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.template_key": %w`, err)}
		}
	}
	if _, ok := etc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EmailTemplate.name"`)}
	}
	if v, ok := etc.mutation.Name(); ok {
		if err := emailtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.name": %w`, err)}
		}
	}
	if _, ok := etc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "EmailTemplate.subject"`)}
	}
	if v, ok := etc.mutation.Subject(); ok {
		if err := emailtemplate.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.subject": %w`, err)}
		}
	}
	if _, ok := etc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "EmailTemplate.body"`)}
	}
	if v, ok := etc.mutation.Body(); ok {
		if err := emailtemplate.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.body": %w`, err)}
		}
	}
	if _, ok := etc.mutation.IsHTML(); !ok {
		return &ValidationError{Name: "is_html", err: errors.New(`ent: missing required field "EmailTemplate.is_html"`)}
	}
	if _, ok := etc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailTemplate.created_at"`)}
	}
	if _, ok := etc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailTemplate.updated_at"`)}
	}
	if _, ok := etc.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "EmailTemplate.is_deleted"`)}
	}
	return nil
}

func (etc *EmailTemplateCreate) sqlSave(ctx context.Context) (*EmailTemplate, error) {
	if err := etc.check(); err != nil {
		return nil, err
	}
	_node, _spec := etc.createSpec()
	if err := sqlgraph.CreateNode(ctx, etc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	etc.mutation.id = &_node.ID
	etc.mutation.done = true
	return _node, nil
}

func (etc *EmailTemplateCreate) createSpec() (*EmailTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailTemplate{config: etc.config}
		_spec = sqlgraph.NewCreateSpec(emailtemplate.Table, sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = etc.conflict
	if id, ok := etc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := etc.mutation.TemplateKey(); ok {
		_spec.SetField(emailtemplate.FieldTemplateKey, field.TypeString, value)
		_node.TemplateKey = value
	}
	if value, ok := etc.mutation.Name(); ok {
		_spec.SetField(emailtemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := etc.mutation.Subject(); ok {
		_spec.SetField(emailtemplate.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := etc.mutation.Body(); ok {
		_spec.SetField(emailtemplate.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := etc.mutation.IsHTML(); ok {
		_spec.SetField(emailtemplate.FieldIsHTML, field.TypeBool, value)
		_node.IsHTML = value
	}
	if value, ok := etc.mutation.CreatedAt(); ok {
		_spec.SetField(emailtemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := etc.mutation.UpdatedAt(); ok {
		_spec.SetField(emailtemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := etc.mutation.IsDeleted(); ok {
		_spec.SetField(emailtemplate.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailTemplate.Create().
//		SetTemplateKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailTemplateUpsert) {
//			SetTemplateKey(v+v).
//		}).
//		Exec(ctx)
func (etc *EmailTemplateCreate) OnConflict(opts ...sql.ConflictOption) *EmailTemplateUpsertOne {
	etc.conflict = opts
	return &EmailTemplateUpsertOne{
		create: etc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (etc *EmailTemplateCreate) OnConflictColumns(columns ...string) *EmailTemplateUpsertOne {
	etc.conflict = append(etc.conflict, sql.ConflictColumns(columns...))
	return &EmailTemplateUpsertOne{
		create: etc,
	}
}

type (
	// EmailTemplateUpsertOne is the builder for "upsert"-ing
	//  one EmailTemplate node.
	EmailTemplateUpsertOne struct {
		create *EmailTemplateCreate
	}

	// EmailTemplateUpsert is the "OnConflict" setter.
	EmailTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetTemplateKey sets the "template_key" field.
func (u *EmailTemplateUpsert) SetTemplateKey(v string) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldTemplateKey, v)
	return u
}

// UpdateTemplateKey sets the "template_key" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateTemplateKey() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldTemplateKey)
	return u
}

// SetName sets the "name" field.
func (u *EmailTemplateUpsert) SetName(v string) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateName() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldName)
	return u
}

// SetSubject sets the "subject" field.
func (u *EmailTemplateUpsert) SetSubject(v string) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateSubject() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldSubject)
	return u
}

// SetBody sets the "body" field.
func (u *EmailTemplateUpsert) SetBody(v string) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateBody() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldBody)
	return u
}

// SetIsHTML sets the "is_html" field.
func (u *EmailTemplateUpsert) SetIsHTML(v bool) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldIsHTML, v)
	return u
}

// UpdateIsHTML sets the "is_html" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateIsHTML() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldIsHTML)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailTemplateUpsert) SetUpdatedAt(v time.Time) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateUpdatedAt() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldUpdatedAt)
	return u
}

// SetIsDeleted sets the "is_deleted" field.
func (u *EmailTemplateUpsert) SetIsDeleted(v bool) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldIsDeleted, v)
	return u
}

// UpdateIsDeleted sets the "is_deleted" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateIsDeleted() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldIsDeleted)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emailtemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailTemplateUpsertOne) UpdateNewValues() *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(emailtemplate.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(emailtemplate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailTemplateUpsertOne) Ignore() *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailTemplateUpsertOne) DoNothing() *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailTemplateCreate.OnConflict
// documentation for more info.
func (u *EmailTemplateUpsertOne) Update(set func(*EmailTemplateUpsert)) *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetTemplateKey sets the "template_key" field.
func (u *EmailTemplateUpsertOne) SetTemplateKey(v string) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetTemplateKey(v)
	})
}

// UpdateTemplateKey sets the "template_key" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateTemplateKey() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateTemplateKey()
	})
}

// SetName sets the "name" field.
func (u *EmailTemplateUpsertOne) SetName(v string) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateName() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateName()
	})
}

// SetSubject sets the "subject" field.
func (u *EmailTemplateUpsertOne) SetSubject(v string) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateSubject() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateSubject()
	})
}

// SetBody sets the "body" field.
func (u *EmailTemplateUpsertOne) SetBody(v string) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateBody() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateBody()
	})
}

// SetIsHTML sets the "is_html" field.
func (u *EmailTemplateUpsertOne) SetIsHTML(v bool) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetIsHTML(v)
	})
}

// UpdateIsHTML sets the "is_html" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateIsHTML() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateIsHTML()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailTemplateUpsertOne) SetUpdatedAt(v time.Time) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateUpdatedAt() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetIsDeleted sets the "is_deleted" field.
func (u *EmailTemplateUpsertOne) SetIsDeleted(v bool) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetIsDeleted(v)
	})
}

// UpdateIsDeleted sets the "is_deleted" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateIsDeleted() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateIsDeleted()
	})
}

// Exec executes the query.
func (u *EmailTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailTemplateUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EmailTemplateUpsertOne.ID is not supported by MySQL driver. Use EmailTemplateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailTemplateUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailTemplateCreateBulk is the builder for creating many EmailTemplate entities in bulk.
type EmailTemplateCreateBulk struct {
	config
	err      error
	builders []*EmailTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailTemplate entities in the database.
func (etcb *EmailTemplateCreateBulk) Save(ctx context.Context) ([]*EmailTemplate, error) {
	if etcb.err != nil {
		return nil, etcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(etcb.builders))
	nodes := make([]*EmailTemplate, len(etcb.builders))
	mutators := make([]Mutator, len(etcb.builders))
	for i := range etcb.builders {
		func(i int, root context.Context) {
			builder := etcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, etcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = etcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, etcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, etcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (etcb *EmailTemplateCreateBulk) SaveX(ctx context.Context) []*EmailTemplate {
	v, err := etcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (etcb *EmailTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := etcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (etcb *EmailTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := etcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailTemplateUpsert) {
//			SetTemplateKey(v+v).
//		}).
//		Exec(ctx)
func (etcb *EmailTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailTemplateUpsertBulk {
	etcb.conflict = opts
	return &EmailTemplateUpsertBulk{
		create: etcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (etcb *EmailTemplateCreateBulk) OnConflictColumns(columns ...string) *EmailTemplateUpsertBulk {
	etcb.conflict = append(etcb.conflict, sql.ConflictColumns(columns...))
	return &EmailTemplateUpsertBulk{
		create: etcb,
	}
}

// EmailTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailTemplate nodes.
type EmailTemplateUpsertBulk struct {
	create *EmailTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emailtemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailTemplateUpsertBulk) UpdateNewValues() *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(emailtemplate.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(emailtemplate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailTemplateUpsertBulk) Ignore() *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailTemplateUpsertBulk) DoNothing() *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *EmailTemplateUpsertBulk) Update(set func(*EmailTemplateUpsert)) *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetTemplateKey sets the "template_key" field.
func (u *EmailTemplateUpsertBulk) SetTemplateKey(v string) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetTemplateKey(v)
	})
}

// UpdateTemplateKey sets the "template_key" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateTemplateKey() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateTemplateKey()
	})
}

// SetName sets the "name" field.
func (u *EmailTemplateUpsertBulk) SetName(v string) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateName() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateName()
	})
}

// SetSubject sets the "subject" field.
func (u *EmailTemplateUpsertBulk) SetSubject(v string) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateSubject() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateSubject()
	})
}

// SetBody sets the "body" field.
func (u *EmailTemplateUpsertBulk) SetBody(v string) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateBody() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateBody()
	})
}

// SetIsHTML sets the "is_html" field.
func (u *EmailTemplateUpsertBulk) SetIsHTML(v bool) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetIsHTML(v)
	})
}

// UpdateIsHTML sets the "is_html" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateIsHTML() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateIsHTML()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EmailTemplateUpsertBulk) SetUpdatedAt(v time.Time) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateUpdatedAt() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetIsDeleted sets the "is_deleted" field.
func (u *EmailTemplateUpsertBulk) SetIsDeleted(v bool) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetIsDeleted(v)
	})
}

// UpdateIsDeleted sets the "is_deleted" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateIsDeleted() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateIsDeleted()
	})
}

// Exec executes the query.
func (u *EmailTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
